name: Boatrace Automation

on:
  schedule:
    # 毎日日本時間の20:00（UTC 11:00）に定期実行
    - cron: '0 11 * * *'
  workflow_dispatch: # GitHubの画面から手動実行できるようにする設定

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py
